# BackEnd_Equipo3/Dockerfile.producers
FROM python:3.11-slim

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiamos solo lo necesario
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./producers /app/producers

WORKDIR /app/producers

# Ejecutar TODOS los productores al iniciar el contenedor
CMD ["bash", "/app/wait-for-kafka.sh"]
