# BackEnd_Equipo3/Dockerfile.producers
FROM python:3.11-slim

WORKDIR /app

# Copiamos solo lo necesario
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./producers /app/producers

WORKDIR /app/producers

# Ejecutar TODOS los productores al iniciar el contenedor
CMD ["bash", "-c", "python productor_calidad_aire.py & python productor_sonido.py & python productor_soterrado.py & tail -f /dev/null"]
